spring:
  application:
    name: artifact-distribution
  r2dbc:
    url: r2dbc:h2:file:///./data/testdb;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=true
server:
  port: 9080
logging:
  level:
    org.springframework.r2dbc: DEBUG
files:
  uploaded:
    dir: /tmp/data