apiVersion: v1
kind: Service

metadata:
  name: artifact-server

spec:
  selector:
    app: artifact-server

  ports:
    - name: http
      port: 9080
      targetPort: 9080
      nodePort: 30080
    - name: grpc
      port: 9090
      targetPort: 9090

  type: NodePort